### PR TITLE
Added missing dependency.

### PR DESCRIPTION
**Pull request by skasperski**

### CODE REVIEW

**Review by jhidalgocarrio — CHANGES_REQUESTED** [review]
Better in:
DEPS_PLAIN
     Boost_SERIALIZATION

**Comment by jhidalgocarrio** [comment]
Actually this is also done at coverage_map branch in [CMakelists.txt](https://github.com/envire/slam-maps/blob/coverage_map/src/CMakeLists.txt#L60)

**Review by annaborn — COMMENTED** [review]
There is Boost_SERIALIZATION in DEPS_PLAIN.
So no need to add it in DEPS_PKGCONFIG.
see [CMakeList.txt](https://github.com/envire/slam-maps/blob/master/src/CMakeLists.txt)

@jhidalgocarrio it is also done at master branch

**Comment by skasperski** [comment]
It is there, but it gives me this when compiling:
```
[ 10%] Building CXX object src/CMakeFiles/maps.dir/grid/ElevationMap.cpp.o
In file included from /home/dfki.uni-bremen.de/skasperski/Robotics/slam3d/slam/maps/src/grid/GridMap.hpp:39:0,
                 from /home/dfki.uni-bremen.de/skasperski/Robotics/slam3d/slam/maps/src/grid/ElevationMap.hpp:30,
                 from /home/dfki.uni-bremen.de/skasperski/Robotics/slam3d/slam/maps/src/grid/ElevationMap.cpp:27:
/home/dfki.uni-bremen.de/skasperski/Robotics/slam3d/slam/maps/build/include/_maps_/maps/LocalMap.hpp:37:46: fatal error: boost_serialization/EigenTypes.hpp: No such file or directory
compilation terminated.
```

**Comment by chhtz** [comment]
`boost_serialization` refers to what gets compiled from `base/boost_serialization` (which itself depends on the `Boost_SERIALIZATION` library). And this is indeed a required dependency.

**Pull request merged**
