### PR TITLE
Cherry pick coverage map 

### PR DESCRIPTION
**Pull request by arneboe**
This cherry picks the coverage map commits

### CODE REVIEW

**Comment by chhtz** [comment]
Given the amount of FIXMEs and TODOs I see why we might have been reluctant to merge this into master. Especially, this does not calculate the actual coverage (which would require some sort of ray-tracing of laser-beams/layers). But instead it just covers a ball around a given center point (which on the other hand is good enough for many applications).

**Comment by arneboe** [comment]
True, however the AreaExplorer from the ugv_nav4d package depends on this functionality. And we need the planner in the student project and possibly in transfit. 
Maybe we can merge this and find a student to fix the shortcomings? :)

**Comment by chhtz** [comment]
If the current functionality is "good enough", we could just remove the `mls` member and all accesses to it. (I'm not 100% sure anymore, why we had this in the first place)

Maybe also remove the `base::AngleSegment` parameter of `addCoverage`.

----

If this is too much effort, I won't strongly object just merging as it is, though.

**Comment by skasperski** [comment]
Update: Should now be able to merge again.

**Pull request merged**
