### PR TITLE
QT MOC exclude of types in viz

### PR DESCRIPTION
**Pull request by planthaber**
fixes incompatibilities of the visualization with QT

### CODE REVIEW

**Comment by saarnold** [comment]
Just out of curiosity, what is the problem with those headers?

**Comment by planthaber** [comment]
https://bugreports.qt.io/browse/QTBUG-22829

3rd Answer:
```
This is a major change and will never be backported to Qt4
Until you port your code to Qt5, you can use this work around of wrapping any problematic include within #ifndef Q_MOC_RUN:

#ifndef Q_MOC_RUN
#include <boost/python.hpp>
#endif
```

**Comment by saarnold** [comment]
My question was what qualifies a header to be problematic for Qt5?

**Comment by arneboe** [comment]
I dont remember what exactly the problem was, just that excluding fixed it.
I guess we could remove the ifdef and see what happens

Sascha Arnold <notifications@github.com> schrieb am Do., 13. Sep. 2018
17:57:

**Comment by planthaber** [comment]
New features in boost are incompatible with the MOC from QT4. 

It is similar to this:
https://github.com/envire/envire-envire_core

We already had an discussionsomewhere else, where the decision was to add ```QT_VERSION >= 0x050000``` to document that qt5 is not affected.

The header only gets excluded, when qt less than 5 runs its MOC.

**Comment by chhtz** [comment]
I don't think this patch breaks anything. [At the other place in envire_core](https://github.com/envire/envire-envire_core/blob/master/viz/EnvireGraphStructureVisualization/EnvireGraphStructureVisualization.hpp#L33) which @planthaber mentioned, we simply put a comment why this is necessary.
I'm fine with either putting a comment, or having that additional `QT_VERSION >= 0x050000`, or both.

**Comment by saarnold** [comment]
I'm fine with the fix. I was just interested to find out which headers might be problematic.

**Comment by planthaber** [comment]
> Am 27.09.2018 um 15:25 schrieb Sascha Arnold <notifications@github.com>:
> 
> I'm fine with the fix. I was just interested to find out which headers might be problematic.
> 
Somewhere deep inside boost, didn‘t track it down.

**Pull request merged**
